/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	networkv1beta1 "github.com/ysicing/cloudflow/apis/network/v1beta1"
	versioned "github.com/ysicing/cloudflow/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ysicing/cloudflow/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/ysicing/cloudflow/pkg/client/listers/network/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterEndpointInformer provides access to a shared informer and lister for
// ClusterEndpoints.
type ClusterEndpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ClusterEndpointLister
}

type clusterEndpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterEndpointInformer constructs a new informer for ClusterEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterEndpointInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterEndpointInformer constructs a new informer for ClusterEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkV1beta1().ClusterEndpoints(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkV1beta1().ClusterEndpoints(namespace).Watch(context.TODO(), options)
			},
		},
		&networkv1beta1.ClusterEndpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterEndpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterEndpointInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterEndpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&networkv1beta1.ClusterEndpoint{}, f.defaultInformer)
}

func (f *clusterEndpointInformer) Lister() v1beta1.ClusterEndpointLister {
	return v1beta1.NewClusterEndpointLister(f.Informer().GetIndexer())
}
