/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/ysicing/cloudflow/pkg/client/clientset/versioned/typed/network/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNetworkV1beta1 struct {
	*testing.Fake
}

func (c *FakeNetworkV1beta1) ClusterEndpoints(namespace string) v1beta1.ClusterEndpointInterface {
	return &FakeClusterEndpoints{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNetworkV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
