/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/ysicing/cloudflow/apis/network/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterEndpoints implements ClusterEndpointInterface
type FakeClusterEndpoints struct {
	Fake *FakeNetworkV1beta1
	ns   string
}

var clusterendpointsResource = schema.GroupVersionResource{Group: "network.ysicing.me", Version: "v1beta1", Resource: "clusterendpoints"}

var clusterendpointsKind = schema.GroupVersionKind{Group: "network.ysicing.me", Version: "v1beta1", Kind: "ClusterEndpoint"}

// Get takes name of the clusterEndpoint, and returns the corresponding clusterEndpoint object, and an error if there is any.
func (c *FakeClusterEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ClusterEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterendpointsResource, c.ns, name), &v1beta1.ClusterEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterEndpoint), err
}

// List takes label and field selectors, and returns the list of ClusterEndpoints that match those selectors.
func (c *FakeClusterEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ClusterEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterendpointsResource, clusterendpointsKind, c.ns, opts), &v1beta1.ClusterEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ClusterEndpointList{ListMeta: obj.(*v1beta1.ClusterEndpointList).ListMeta}
	for _, item := range obj.(*v1beta1.ClusterEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterEndpoints.
func (c *FakeClusterEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterendpointsResource, c.ns, opts))

}

// Create takes the representation of a clusterEndpoint and creates it.  Returns the server's representation of the clusterEndpoint, and an error, if there is any.
func (c *FakeClusterEndpoints) Create(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.CreateOptions) (result *v1beta1.ClusterEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterendpointsResource, c.ns, clusterEndpoint), &v1beta1.ClusterEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterEndpoint), err
}

// Update takes the representation of a clusterEndpoint and updates it. Returns the server's representation of the clusterEndpoint, and an error, if there is any.
func (c *FakeClusterEndpoints) Update(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.UpdateOptions) (result *v1beta1.ClusterEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterendpointsResource, c.ns, clusterEndpoint), &v1beta1.ClusterEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterEndpoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterEndpoints) UpdateStatus(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.UpdateOptions) (*v1beta1.ClusterEndpoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterendpointsResource, "status", c.ns, clusterEndpoint), &v1beta1.ClusterEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterEndpoint), err
}

// Delete takes name of the clusterEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeClusterEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterendpointsResource, c.ns, name, opts), &v1beta1.ClusterEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterendpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ClusterEndpointList{})
	return err
}

// Patch applies the patch and returns the patched clusterEndpoint.
func (c *FakeClusterEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterendpointsResource, c.ns, name, pt, data, subresources...), &v1beta1.ClusterEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterEndpoint), err
}
