/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// GenTLSListerExpansion allows custom methods to be added to
// GenTLSLister.
type GenTLSListerExpansion interface{}

// GenTLSNamespaceListerExpansion allows custom methods to be added to
// GenTLSNamespaceLister.
type GenTLSNamespaceListerExpansion interface{}

// InitNasListerExpansion allows custom methods to be added to
// InitNasLister.
type InitNasListerExpansion interface{}

// InitNasNamespaceListerExpansion allows custom methods to be added to
// InitNasNamespaceLister.
type InitNasNamespaceListerExpansion interface{}
