/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1beta1 "github.com/ysicing/cloudflow/apis/apps/v1beta1"
	jobsv1beta1 "github.com/ysicing/cloudflow/apis/jobs/v1beta1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=apps.ysicing.me, Version=v1beta1
	case v1beta1.SchemeGroupVersion.WithResource("webs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Apps().V1beta1().Webs().Informer()}, nil

		// Group=jobs.ysicing.me, Version=v1beta1
	case jobsv1beta1.SchemeGroupVersion.WithResource("gentlss"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Jobs().V1beta1().GenTLSs().Informer()}, nil
	case jobsv1beta1.SchemeGroupVersion.WithResource("initnases"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Jobs().V1beta1().InitNases().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
