# permissions for end users to edit gentls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gentls-editor-role
rules:
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls/status
  verbs:
  - get
