# permissions for end users to view gentls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gentls-viewer-role
rules:
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls/status
  verbs:
  - get
