# permissions for end users to edit initnas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: initnas-editor-role
rules:
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas/status
  verbs:
  - get
