# permissions for end users to view initnas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: initnas-viewer-role
rules:
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas/status
  verbs:
  - get
