---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.ysicing.me
  resources:
  - webs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ysicing.me
  resources:
  - webs/finalizers
  verbs:
  - update
- apiGroups:
  - apps.ysicing.me
  resources:
  - webs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls/finalizers
  verbs:
  - update
- apiGroups:
  - jobs.ysicing.me
  resources:
  - gentls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas/finalizers
  verbs:
  - update
- apiGroups:
  - jobs.ysicing.me
  resources:
  - initnas/status
  verbs:
  - get
  - patch
  - update
