/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/ysicing/cloudflow/apis/network/v1beta1"
	scheme "github.com/ysicing/cloudflow/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterEndpointsGetter has a method to return a ClusterEndpointInterface.
// A group's client should implement this interface.
type ClusterEndpointsGetter interface {
	ClusterEndpoints(namespace string) ClusterEndpointInterface
}

// ClusterEndpointInterface has methods to work with ClusterEndpoint resources.
type ClusterEndpointInterface interface {
	Create(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.CreateOptions) (*v1beta1.ClusterEndpoint, error)
	Update(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.UpdateOptions) (*v1beta1.ClusterEndpoint, error)
	UpdateStatus(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.UpdateOptions) (*v1beta1.ClusterEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ClusterEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ClusterEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterEndpoint, err error)
	ClusterEndpointExpansion
}

// clusterEndpoints implements ClusterEndpointInterface
type clusterEndpoints struct {
	client rest.Interface
	ns     string
}

// newClusterEndpoints returns a ClusterEndpoints
func newClusterEndpoints(c *NetworkV1beta1Client, namespace string) *clusterEndpoints {
	return &clusterEndpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterEndpoint, and returns the corresponding clusterEndpoint object, and an error if there is any.
func (c *clusterEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ClusterEndpoint, err error) {
	result = &v1beta1.ClusterEndpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterEndpoints that match those selectors.
func (c *clusterEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ClusterEndpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ClusterEndpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterEndpoints.
func (c *clusterEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterEndpoint and creates it.  Returns the server's representation of the clusterEndpoint, and an error, if there is any.
func (c *clusterEndpoints) Create(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.CreateOptions) (result *v1beta1.ClusterEndpoint, err error) {
	result = &v1beta1.ClusterEndpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterEndpoint and updates it. Returns the server's representation of the clusterEndpoint, and an error, if there is any.
func (c *clusterEndpoints) Update(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.UpdateOptions) (result *v1beta1.ClusterEndpoint, err error) {
	result = &v1beta1.ClusterEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterendpoints").
		Name(clusterEndpoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterEndpoint).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterEndpoints) UpdateStatus(ctx context.Context, clusterEndpoint *v1beta1.ClusterEndpoint, opts v1.UpdateOptions) (result *v1beta1.ClusterEndpoint, err error) {
	result = &v1beta1.ClusterEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterendpoints").
		Name(clusterEndpoint.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterEndpoint and deletes it. Returns an error if one occurs.
func (c *clusterEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterendpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterendpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterEndpoint.
func (c *clusterEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterEndpoint, err error) {
	result = &v1beta1.ClusterEndpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterendpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
