/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/ysicing/cloudflow/pkg/client/clientset/versioned/typed/jobs/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeJobsV1beta1 struct {
	*testing.Fake
}

func (c *FakeJobsV1beta1) GenTLSs(namespace string) v1beta1.GenTLSInterface {
	return &FakeGenTLSs{c, namespace}
}

func (c *FakeJobsV1beta1) InitNases(namespace string) v1beta1.InitNasInterface {
	return &FakeInitNases{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeJobsV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
