/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/ysicing/cloudflow/apis/jobs/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGenTLSs implements GenTLSInterface
type FakeGenTLSs struct {
	Fake *FakeJobsV1beta1
	ns   string
}

var gentlssResource = schema.GroupVersionResource{Group: "jobs.ysicing.me", Version: "v1beta1", Resource: "gentlss"}

var gentlssKind = schema.GroupVersionKind{Group: "jobs.ysicing.me", Version: "v1beta1", Kind: "GenTLS"}

// Get takes name of the genTLS, and returns the corresponding genTLS object, and an error if there is any.
func (c *FakeGenTLSs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GenTLS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gentlssResource, c.ns, name), &v1beta1.GenTLS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GenTLS), err
}

// List takes label and field selectors, and returns the list of GenTLSs that match those selectors.
func (c *FakeGenTLSs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GenTLSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gentlssResource, gentlssKind, c.ns, opts), &v1beta1.GenTLSList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GenTLSList{ListMeta: obj.(*v1beta1.GenTLSList).ListMeta}
	for _, item := range obj.(*v1beta1.GenTLSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested genTLSs.
func (c *FakeGenTLSs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gentlssResource, c.ns, opts))

}

// Create takes the representation of a genTLS and creates it.  Returns the server's representation of the genTLS, and an error, if there is any.
func (c *FakeGenTLSs) Create(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.CreateOptions) (result *v1beta1.GenTLS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gentlssResource, c.ns, genTLS), &v1beta1.GenTLS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GenTLS), err
}

// Update takes the representation of a genTLS and updates it. Returns the server's representation of the genTLS, and an error, if there is any.
func (c *FakeGenTLSs) Update(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.UpdateOptions) (result *v1beta1.GenTLS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gentlssResource, c.ns, genTLS), &v1beta1.GenTLS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GenTLS), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGenTLSs) UpdateStatus(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.UpdateOptions) (*v1beta1.GenTLS, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gentlssResource, "status", c.ns, genTLS), &v1beta1.GenTLS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GenTLS), err
}

// Delete takes name of the genTLS and deletes it. Returns an error if one occurs.
func (c *FakeGenTLSs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gentlssResource, c.ns, name, opts), &v1beta1.GenTLS{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGenTLSs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gentlssResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GenTLSList{})
	return err
}

// Patch applies the patch and returns the patched genTLS.
func (c *FakeGenTLSs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GenTLS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gentlssResource, c.ns, name, pt, data, subresources...), &v1beta1.GenTLS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.GenTLS), err
}
