/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/ysicing/cloudflow/apis/jobs/v1beta1"
	scheme "github.com/ysicing/cloudflow/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GenTLSsGetter has a method to return a GenTLSInterface.
// A group's client should implement this interface.
type GenTLSsGetter interface {
	GenTLSs(namespace string) GenTLSInterface
}

// GenTLSInterface has methods to work with GenTLS resources.
type GenTLSInterface interface {
	Create(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.CreateOptions) (*v1beta1.GenTLS, error)
	Update(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.UpdateOptions) (*v1beta1.GenTLS, error)
	UpdateStatus(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.UpdateOptions) (*v1beta1.GenTLS, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.GenTLS, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.GenTLSList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GenTLS, err error)
	GenTLSExpansion
}

// genTLSs implements GenTLSInterface
type genTLSs struct {
	client rest.Interface
	ns     string
}

// newGenTLSs returns a GenTLSs
func newGenTLSs(c *JobsV1beta1Client, namespace string) *genTLSs {
	return &genTLSs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the genTLS, and returns the corresponding genTLS object, and an error if there is any.
func (c *genTLSs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GenTLS, err error) {
	result = &v1beta1.GenTLS{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gentlss").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GenTLSs that match those selectors.
func (c *genTLSs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GenTLSList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.GenTLSList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gentlss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested genTLSs.
func (c *genTLSs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gentlss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a genTLS and creates it.  Returns the server's representation of the genTLS, and an error, if there is any.
func (c *genTLSs) Create(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.CreateOptions) (result *v1beta1.GenTLS, err error) {
	result = &v1beta1.GenTLS{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gentlss").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(genTLS).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a genTLS and updates it. Returns the server's representation of the genTLS, and an error, if there is any.
func (c *genTLSs) Update(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.UpdateOptions) (result *v1beta1.GenTLS, err error) {
	result = &v1beta1.GenTLS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gentlss").
		Name(genTLS.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(genTLS).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *genTLSs) UpdateStatus(ctx context.Context, genTLS *v1beta1.GenTLS, opts v1.UpdateOptions) (result *v1beta1.GenTLS, err error) {
	result = &v1beta1.GenTLS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gentlss").
		Name(genTLS.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(genTLS).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the genTLS and deletes it. Returns an error if one occurs.
func (c *genTLSs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gentlss").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *genTLSs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gentlss").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched genTLS.
func (c *genTLSs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GenTLS, err error) {
	result = &v1beta1.GenTLS{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gentlss").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
