/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/ysicing/cloudflow/apis/jobs/v1beta1"
	scheme "github.com/ysicing/cloudflow/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InitNasesGetter has a method to return a InitNasInterface.
// A group's client should implement this interface.
type InitNasesGetter interface {
	InitNases(namespace string) InitNasInterface
}

// InitNasInterface has methods to work with InitNas resources.
type InitNasInterface interface {
	Create(ctx context.Context, initNas *v1beta1.InitNas, opts v1.CreateOptions) (*v1beta1.InitNas, error)
	Update(ctx context.Context, initNas *v1beta1.InitNas, opts v1.UpdateOptions) (*v1beta1.InitNas, error)
	UpdateStatus(ctx context.Context, initNas *v1beta1.InitNas, opts v1.UpdateOptions) (*v1beta1.InitNas, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.InitNas, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.InitNasList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.InitNas, err error)
	InitNasExpansion
}

// initNases implements InitNasInterface
type initNases struct {
	client rest.Interface
	ns     string
}

// newInitNases returns a InitNases
func newInitNases(c *JobsV1beta1Client, namespace string) *initNases {
	return &initNases{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the initNas, and returns the corresponding initNas object, and an error if there is any.
func (c *initNases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.InitNas, err error) {
	result = &v1beta1.InitNas{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("initnases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InitNases that match those selectors.
func (c *initNases) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.InitNasList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.InitNasList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("initnases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested initNases.
func (c *initNases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("initnases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a initNas and creates it.  Returns the server's representation of the initNas, and an error, if there is any.
func (c *initNases) Create(ctx context.Context, initNas *v1beta1.InitNas, opts v1.CreateOptions) (result *v1beta1.InitNas, err error) {
	result = &v1beta1.InitNas{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("initnases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(initNas).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a initNas and updates it. Returns the server's representation of the initNas, and an error, if there is any.
func (c *initNases) Update(ctx context.Context, initNas *v1beta1.InitNas, opts v1.UpdateOptions) (result *v1beta1.InitNas, err error) {
	result = &v1beta1.InitNas{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("initnases").
		Name(initNas.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(initNas).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *initNases) UpdateStatus(ctx context.Context, initNas *v1beta1.InitNas, opts v1.UpdateOptions) (result *v1beta1.InitNas, err error) {
	result = &v1beta1.InitNas{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("initnases").
		Name(initNas.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(initNas).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the initNas and deletes it. Returns an error if one occurs.
func (c *initNases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("initnases").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *initNases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("initnases").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched initNas.
func (c *initNases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.InitNas, err error) {
	result = &v1beta1.InitNas{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("initnases").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
