apiVersion: apps.ysicing.me/v1beta1
kind: Web
metadata:
  name: whoami
  namespace: cce-system
spec:
  image: ccr.ccs.tencentyun.com/k7scn/whoami:2022
  replicas: 2
  service:
    ports:
      - name: http-32379
        port: 32379
  ingress:
    class: nginx
    hostname: whoami.external.ysicing.net
    port: 32379
    tls: "tls-ysicing-net"
