apiVersion: apps.ysicing.me/v1beta1
kind: Web
metadata:
  name: web-sample
spec:
  image: nginx
  replicas: 1
  # service:
  #   ports:
  #     - name: http-80
  #       port: 80
  # ingress:
  #   class: nginx
  #   hostname: example.com
  #   port: 80
  #   tls: ""
