/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ClusterEndpointListerExpansion allows custom methods to be added to
// ClusterEndpointLister.
type ClusterEndpointListerExpansion interface{}

// ClusterEndpointNamespaceListerExpansion allows custom methods to be added to
// ClusterEndpointNamespaceLister.
type ClusterEndpointNamespaceListerExpansion interface{}
