/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	jobsv1beta1 "github.com/ysicing/cloudflow/apis/jobs/v1beta1"
	versioned "github.com/ysicing/cloudflow/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ysicing/cloudflow/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/ysicing/cloudflow/pkg/client/listers/jobs/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GenTLSInformer provides access to a shared informer and lister for
// GenTLSs.
type GenTLSInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.GenTLSLister
}

type genTLSInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGenTLSInformer constructs a new informer for GenTLS type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGenTLSInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGenTLSInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGenTLSInformer constructs a new informer for GenTLS type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGenTLSInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobsV1beta1().GenTLSs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobsV1beta1().GenTLSs(namespace).Watch(context.TODO(), options)
			},
		},
		&jobsv1beta1.GenTLS{},
		resyncPeriod,
		indexers,
	)
}

func (f *genTLSInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGenTLSInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *genTLSInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&jobsv1beta1.GenTLS{}, f.defaultInformer)
}

func (f *genTLSInformer) Lister() v1beta1.GenTLSLister {
	return v1beta1.NewGenTLSLister(f.Informer().GetIndexer())
}
