/*
AGPL License
Copyright 2022 ysicing(i@ysicing.me).
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/ysicing/cloudflow/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// GenTLSs returns a GenTLSInformer.
	GenTLSs() GenTLSInformer
	// InitNases returns a InitNasInformer.
	InitNases() InitNasInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// GenTLSs returns a GenTLSInformer.
func (v *version) GenTLSs() GenTLSInformer {
	return &genTLSInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// InitNases returns a InitNasInformer.
func (v *version) InitNases() InitNasInformer {
	return &initNasInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
