apiVersion: apps.ysicing.cloud/v1beta1
kind: Web
metadata:
  name: mysql
spec:
  image: docker.io/bitnami/mysql:8.0
  replicas: 1
  envs:
    - name: MYSQL_DATABASE
      value: demo
    - name: MYSQL_ROOT_PASSWORD
      value: sieraz4quahxavaetahFieg9eishaeph
    - name: BITNAMI_DEBUG
      value: "true"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  volume:
    mountPaths:
      - mountPath: /bitnami/mysql/data
    type: pvc
  service:
    ports:
    - port: 3306
