name: flow

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '**.go'
    tags:
      - v*

jobs:
  flow:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install kind
        uses: helm/kind-action@v1.7.0
      - name: install kubectl
        uses: azure/setup-kubectl@v3.2
      - name: install helm
        uses: azure/setup-helm@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Install GoTools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/google/addlicense@latest
          go install golang.org/x/tools/cmd/goimports@latest
      - name: build
        run: |
          make kustomize
          make controller-gen
          make crd
          make release
      - uses: peter-evans/create-pull-request@v4
        with:
          title: 'feat(update): updated dev yaml'
          commit-message: 'update dev yaml'
          branch: create-pull-request/dev
          signoff: true
      - name: Install CloudFlow Operator
        run: |
          kubectl create namespace cce-system
          kubectl apply -f hack/deploy/deploy.yaml
          kubectl get pods -n cce-system
          kubectl apply -f config/samples/apps_v1beta1_web.yaml
          kubectl apply -f config/samples/web

